---
- name: Criar usuário IAM na AWS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Criar o usuário IAM 'exemplo-usuario'
      amazon.aws.iam_user:
        name: maria
        state: present
      register: resultado_criacao

    - name: Exibir resultado da criação
      debug:

        var: resultado_criacao
