---
- name: Criar VPC, Subnet e VM básica no AWS EC2
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  tasks:
    - name: Criar VPC básica
      ec2_vpc_net:
        name: basic-vpc
        cidr_block: 10.0.0.0/16
        region: us-east-2
        state: present
        tags:
          Name: basic-vpc
      register: vpc

    - name: Criar Subnet na VPC
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.1.0/24
        az: us-east-2a
        region: us-east-2
        state: present
        tags:
          Name: basic-subnet
      register: subnet

    - name: Lançar instância EC2 básica na subnet
      ec2_instance:
        name: basic-vm
        image_id: ami-0ff8a91507f77f867
        instance_type: t2.micro
        region: us-east-2
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        state: present
        tags:
          Name: basic-vm
      register: ec2

    - name: Mostrar IDs criados
      debug:
        msg: 
          - "VPC ID: {{ vpc.vpc.id }}"
          - "Subnet ID: {{ subnet.subnet.id }}"
          - "Instância ID: {{ ec2.instances[0].instance_id }}"
