---
- name: Criar VM básica no AWS EC2
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  tasks:
    - name: Lançar instância EC2 básica
      ec2_instance:
        name: basic-vm-ansible
        image_id: ami-0ff8a91507f77f867
        instance_type: t2.micro
        region: us-east-2
        state: present
        tags:
          Name: basic-vm
      register: ec2

    - name: Mostrar ID da instância
      debug:
        msg: "Instância criada com ID: {{ ec2.instances[0].instance_id }}"