---
- name: Demo Provisionamento AWS do Zero com Ansible
  hosts: localhost
  gather_facts: true  # Coleta IP do host para SG
  vars:
    regiao: "us-east-2"
    nome_vpc: "Demo-VPC-Ansible"
    cidr_vpc: "10.0.0.0/16"
    cidr_subnet: "10.0.1.0/24"
    nome_subnet: "Demo-Subnet-Publica"
    nome_igw: "Demo-IGW"
    nome_rt: "Demo-RouteTable"
    nome_sg: "Demo-SG-SSH"
    nome_key: "demo-key-ansible"
    nome_instancia: "Demo-EC2"
    tipo_instancia: "t3.micro"
    meu_ip: "{{ ansible_host_ip | default('0.0.0.0/0') }}"  # Seu IP para SSH; fixe para segurança
  tasks:
    - name: Criar VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ nome_vpc }}"
        cidr_block: "{{ cidr_vpc }}"
        region: "{{ regiao }}"
        state: present
      register: vpc_result

    - name: Pegar ID da VPC
      set_fact:
        vpc_id: "{{ vpc_result.vpc.id }}"

    - name: Criar Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        name: "{{ nome_igw }}"
        region: "{{ regiao }}"
        state: present
      register: igw_result

    - name: Criar Sub-rede Pública
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ cidr_subnet }}"
        az: "{{ regiao }}a"  # AZ padrão
        name: "{{ nome_subnet }}"
        map_public: true  # Auto-assign public IP
        region: "{{ regiao }}"
        state: present
      register: subnet_result

    - name: Criar Route Table e Associar à Sub-rede
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        name: "{{ nome_rt }}"
        region: "{{ regiao }}"
        state: present
      register: rt_result

    - name: Adicionar Rota Default para IGW na Route Table
      amazon.aws.ec2_vpc_route:
        route_table_id: "{{ rt_result.route_tables[0].id }}"
        destination_cidr_block: "0.0.0.0/0"
        gateway_id: "{{ igw_result.gateway_id }}"
        region: "{{ regiao }}"
        state: present

    - name: Associar Route Table à Sub-rede
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        subnet_id: "{{ subnet_result.subnet.id }}"
        route_table: "{{ rt_result.route_tables[0].id }}"
        region: "{{ regiao }}"
        state: present

    - name: Criar Security Group para SSH
      amazon.aws.ec2_group:
        name: "{{ nome_sg }}"
        description: "SG para SSH na demo Ansible"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ meu_ip }}/32"  # Seu IP apenas
        region: "{{ regiao }}"
        state: present
      register: sg_result

    - name: Criar Key Pair SSH
      amazon.aws.ec2_key:
        name: "{{ nome_key }}"
        region: "{{ regiao }}"
        state: present
      register: key_result
      # A chave privada é salva em files/ se não existir; baixe manualmente se precisar

    - name: Lançar Instância EC2
      amazon.aws.ec2_instance:
        name: "{{ nome_instancia }}"
        key_name: "{{ nome_key }}"
        instance_type: "{{ tipo_instancia }}"
        security_group: "{{ nome_sg }}"
        image_id: "resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"  # Latest AL2 via SSM
        network:
          vpc_id: "{{ vpc_id }}"
          subnets:
            - "{{ subnet_result.subnet.id }}"
        wait: true
        count: 1
        region: "{{ regiao }}"
        state: present
      register: ec2_result

    - name: Exibir Resumo da Demo
      debug:
        msg: |
          Demo Concluída! Infra provisionada na AWS:
          - VPC ID: {{ vpc_id }}
          - Sub-rede ID: {{ subnet_result.subnet.id }}
          - SG ID: {{ sg_result.group_id }}
          - Key Pair: {{ nome_key }} (chave privada em {{ key_result.private_key_out }} se gerada)
          - EC2 ID: {{ ec2_result.instances[0].instance_id }}
          - IP Público: {{ ec2_result.instances[0].public_ip_address }}
          Para SSH: ssh -i {{ nome_key }}.pem ec2-user@{{ ec2_result.instances[0].public_ip_address }}
          Verifique no Console AWS: EC2 > Instances/VPCs.

# Para Cleanup (rode separadamente com state: absent em tasks relevantes)
# - name: Destruir Recursos
#   amazon.aws.ec2_instance: ... state: absent
#   (Repita para VPC, etc.)