---
- name: Criar VPC, Subnet e VM básica no AWS EC2 com AMI dinâmica (us-east-2) - Filters corrigidos
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  tasks:
    - name: Criar VPC básica
      ec2_vpc_net:
        name: basic-vpc
        cidr_block: 10.0.0.0/16
        region: us-east-2
        state: present
        tags:
          Name: basic-vpc
      register: vpc

    - name: Criar Subnet na VPC
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.1.0/24
        az: us-east-2a
        region: us-east-2
        state: present
        tags:
          Name: basic-subnet
      register: subnet

    - name: Buscar a AMI mais recente do Amazon Linux 2
      ec2_ami_info:
        region: us-east-2
        owners:
          - amazon
        filters:
          name: amzn2-ami-hvm-*-x86_64-gp2
          architecture: x86_64
          root-device-type: ebs
          virtualization-type: hvm
        sort:
          - creation_date
        sort_order: descending
      register: al2_amis

    - name: Definir variável para a AMI mais recente
      set_fact:
        latest_al2_ami_id: "{{ al2_amis.images[0].image_id }}"

    - name: Lançar instância EC2 básica na subnet com AMI dinâmica
      ec2_instance:
        name: basic-vm
        image_id: "{{ latest_al2_ami_id }}"
        instance_type: t2.micro
        region: us-east-2
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        state: present
        tags:
          Name: basic-vm
      register: ec2

    - name: Mostrar IDs criados e AMI usada
      debug:
        msg: 
          - "AMI ID usada: {{ latest_al2_ami_id }}"
          - "VPC ID: {{ vpc.vpc.id }}"
          - "Subnet ID: {{ subnet.subnet.id }}"
          - "Instância ID: {{ ec2.instances[0].instance_id }}"
