---
- name: Criar Resource Group no Azure
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - azure.azcollection

  vars:
    resource_group: "rg-teste-azure-ansible"
    location: "brazilsouth"

  tasks:
    - name: Criar Resource Group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
        tags:
          Environment: "Teste"
          CreatedBy: "Ansible"
